### ISSUE TITLE
Ambit 2 "Duck" Log File

### ISSUE THREAD

**Issue by Gerold-R** [openambitproject/openambit#119]
Hello
This is not really an openAmbit issue. I am looking for an Ambit 2 "Duck" log file made during a firmware update or a forced firmware update. Is there anyone who can provide me such a file? Personally I only have an Ambit 2S. Thanks in advance.

**Comment by benedetto** [comment]
Possibly, yes. I still have a firmware update pending and will try to take a log from the update process. However, I can't tell when exactly that will be, but I'll try to do it in the nearer future...

**Comment by Gerold-R** [comment]
@benedetto Thank you.

**Comment by benedetto** [comment]
@Gerold-R 

There you go!
[Update.zip](https://github.com/openambitproject/openambit/files/853521/Update.zip)
This should contain the update of my Ambit2 to Firmware 2.0.16 (if I remember the version number correctly). I could not check whether it contains what I expect since I currently do not get the wireshark dissector to work.

It would be nice if you could give me a brief feedback whether you could work with it.

**Comment by Gerold-R** [comment]
Ok. 
Thanks benedetto.

**Comment by Gerold-R** [comment]
Looks like you have hardware version 74.1.19201 (J.1.K.1). I have 75.3.19201. Not sure if I can use it to compare with the capture of my firmware update. Will see.

**Comment by Gerold-R** [comment]
@benedetto 
I could extract all firmware data send to the watch from your capture file and compared it with other firmware data from a capture file of an Ambit2 S with the same hw version 74.1.19201. 
Unfortenatly the data are identical. Thank you anyway.
