### ISSUE TITLE
Suuntoo Ambit 2S broken after using openambit v0.4 

### ISSUE THREAD

**Issue by aicastell** [openambitproject/openambit#197]
I compiled openambit v0.4 fine, but after doing this #195 to try synchronizing my trainings with movescount (I was unable to do that), now I can't start any new training with my Suuntoo ambit 2S watch . When I enter into the menu to start a new training, I see this:

    Err: 62
    Err: 62
    Err: 62
    Err: 62
    Err: 62
    Err: 62

Whenever I click in any of those messages, I get:

    Ningun PDI.

So I can't start a new run, swim, nor bike training. Memory still maintains all the trainings done before using v0.4. But this is not very helpful, I need this clock for my trainings.

Please, help with this would be really appreciated :(

**Comment by gustavo-iniguez-goya** [comment]
Try synchronizing the watch using Movescount app. I ran into a similar problem if not the same (#190), and I managed to fix it syncing it with Movescount app.

**Comment by aicastell** [comment]
The problem is I use openambit because I don't have windows at home. Do you know if movescount works under a virtualbox machine?

**Comment by marguslt** [comment]
Yes, Moveslink2 works just fine in Virtualbox (handy search phrase: "modern.ie vm" ).
Actually Moveslink should work with just Wine as well, but you need some "donor" installation or have to be creative with its config files, take a look at #122.

**Comment by Gerold-R** [comment]
Hi marguslt, I really prefer my own tool (in fact just a new GUI) now using the DLL which comes with Moveslink than working with the original Moveslink2 and WINE. But never used the DLL to flash the firmware.

**Comment by aicastell** [comment]
@marguslt thank you very much. That will be very helpful to fix my issue and recover the watch functionality asap. I need it for my daily trainings. I will try this.

@Gerold-R, I had been using openambit v0.3 for the last three years without any issue related with this Err: 62, and after testing v0.4, this error appeared in my watch. Probably its a coincidence (I was trying to synchronize my trainings to movescount account and tryied several times without success, connecting and disconnecting the watch from the USB cable again and again). If this is a so common issue, it would be nice for all Suntoo users to have a tool available to delete that logbook, in order to recover the whole watch functionality. That would be really helpful, not only for me.

The suggestion for the developer's team would be to integrate that functionality within the openambit user interface. 

Thank you all of you for your support! :) I will come back on this issue when fixed.

**Comment by gustavo-iniguez-goya** [comment]
Yeah @aicastell , I use it from a VM, mainly because the power meter data is not synced to the servers.

**Comment by Gerold-R** [comment]
As I remember well I have read somewhere how to push a move saved by OpenAmbit to Movescount. Maybe it was even here a comment on Github.

At the time I played at lot with my Ambit 2S, I have written a function to save the complete raw logbook data to file (2.750.000 Bytes from address $0F4240). When I delete the sync flag of a move, I do write only one byte back and it works, so writing the complete data back should also work. But would it make sense if you got the error 62 or 12 cause of corrupted logook data? 

As I said, I never used OpenAmbit and I got this error 62 (and error 12) too. So I dont think it's caused by OpenAmbit but a Firmware bug. Or maybe the Flash Memory is defective, but I executed the internal Flash Memory tests (read and write) on the watch and all tests passed successfully. 

![ambit2s flash read test 3 - small](https://user-images.githubusercontent.com/16975317/42309212-3c49baa4-8038-11e8-9e78-ac5d7a3ebbed.jpg)

**Comment by centic9** [comment]
I recently had a similar "Err 62" with a very specific set of sport modes, when changing the sports modes again, it worked again, but that specific set of sport modes broke the watch quite badly and only a forced firmware reset could fix it. 

Maybe some glitch in Openambit with writing the sport-mode data or a firmware bug on the watch as it was reproducibly causing the problem.

However I think the original issue in this issue is resolved, I could not find any way to avoid this from happening in Openambit.

**Comment by centic9** [comment]
By chance I now found a problem that could also be the reason for this issue. 

During writing, the array of bytes is split into packets of 54 bytes, but the handling of the "remainder" was incorrect. If it was "0", Openambit still to send an empty packet, which seems to have confused the watch. 

Simply not trying to write the remaining empty packet seems to fix this for me.
