### ISSUE TITLE
Sync sport modes

### ISSUE THREAD

**Issue by mbernasocchi** [openambitproject/openambit#21]
**HELPING OUT:**
From Windows and moveslink sync a bunch of different sportmodes.
- Start PCAP dump (howto: http://openambit.org/wireshark-dissector)
- Create a bunch of different custom sport modes on movescount.com
- Initiate sync in Moveslink
- Stop PCAP dump
- Send PCAP dump and detailed info about the sport modes to emil at openambit.org

**Comment by superdupersvard** [comment]
I have experimented with this issue and are now able to sync the sport / custom modes to my watch. (The changes are in my fork.)
However there are still some unclear areas.
1. When syncing in Windows and looking at the data sent to the device, I see that in addition to the displays defined at movescount.com site it also sends 5 additional displays to the device for every sport mode. This 5 displays are identical for all the sport modes, at least for me. But I would like to check this with log from others. So if someone has wireshark logs when syncing in Windows, can you please send them to me? To "same username as I have here" @passagen.se.
2. There are some unknown fields in the data sent to the device. In my logs they are all zero (except one field). However, from the JSon-settings file from movescount there are some fildes that I have not been able to set from movescount.com. Do anyone know how to set "TonesMode" and "UseAutomaticLogRecording" for one sport mode and "RequiresHRBelt" for one display?

**Comment by benedetto** [comment]
@superdupersvard That's great news. You have mail, I hope it helps.

**Comment by superdupersvard** [comment]
@benedetto Thanks for the logs. They showed the exact same 5 extra displays.
I am now also able to sync apps. 
If someone wants to try to sync with these changes, please go ahead. Right now the code in my branch will print out all the data sent to the watch to the terminal. (You may have to turn "Sync orbital data" to off, to not also print all the orbital data.) You also have to turn on "Sync sport modes" in the settings (default off). Also the wireshark dissector will print out the sport modes and app data to terminal. This two output should be equal if openambit succeeded to sync the same data as Windows. If you try please report if the two outputs are equal or not.

**Comment by marguslt** [comment]
Nice! Tested with Amibt1, seems to buld and run and sync just fine, at least nothing blew up and my sport modes and apps are still working :) Will check against Moveslink captures in a day or two. 
Whats next, offline settings and sport mode handling? :)

**Comment by superdupersvard** [comment]
@margusit It's nice that it also works with Ambit1. If you have the possibility to take a .pcap log in Windows and e-mail that to me plus the output log from openambit (with the same sport modes setting), then I could check that all the written data is correct for also for Ambit1.
I would also be interested in a Windows .pcap log from someone with an Ambit3 whit a least one sports mode including one or more applications.
The logs can be e-mailed to "same username as I have here" @passagen.se.

**Comment by benedetto** [comment]
@superdupersvard I am using your code now for some time and it hasn't broken my watch (looks like it's not too bad ;-) Thanks for that great work!

However, I have noticed two flaws:

1. Interval timers: I have one Sport mode with an Interval timer set to 20 seconds high, 10 seconds rest. If I sync this to my watch with openambit instead of movescount, it ends up on the watch as 0 meters high, 10 meters rest. So obviously your code does somehow change the setting from time to distance here.

1. Heart rate graph: For the screens where a graph is shown the watch has two types of graphs, either a simple line or a bar-like graph where the area under the line is filled. If I get it right – I'm only guessing here – then the line graph can have floating upper and lower boundaries (i.e. the vertical range is chosen in a way that the data range fits into it but is spread is wide as possible) while the bar-like one seems to have its lower boundary fixed at 0 and only the upper boundary is adjusted. If I sync my sport modes with movescount, heart rate graphs are displayed as line graphs and for example for elevation the bar-like graph is used. On your code it looks like all graphs are bar-like which makes this type of screen quite useless for some information types (e.g. heart rate).

I haven't .pcap logs of such a transfer yet, but if you need, I could try to record some when I do a Windows sync the next time.

**Comment by superdupersvard** [comment]
@benedetto Thanks for the feedback. 
I have now updated the code with (hopefully) fixes for the two bugs that you found. I have tested with graphs for altitude, heart rate and barograph, and now openambit should sends the same data as in Windows. Please try and let me know if it works for you.

**Comment by benedetto** [comment]
@superdupersvard sorry for not answering for so long, but I had some busy weeks now and not much time to use my watch (unfortunately...) Now that things tend to get a bit more calm again I'll see that I can give it a go in the nearer future.

**Comment by benedetto** [comment]
@superdupersvard finally I have found the time to test both issues and now it works as expected. Also I did not experience any other issues related to the sort mode syncing.  

So I would love to see your code merged into master!

**Comment by fatualux** [comment]
Hi all.
I have encountered this error when trying to synchronize sport modes:
#ASSERT failure in QList<T>::at: "index out of range", file /usr/include/qt4/QtCore/qlist.h, line 469
Openambit crashes when "Fetching sport modes" is displayed on the GUI.
The only way to complete the synchronization is to remove the flag on "Sync sport modes (from Movescount).
Any suggestion? Thanks
