### ISSUE TITLE
Problem with openambit2gpx.py

### ISSUE THREAD

**Issue by myadzel** [openambitproject/openambit#233]
>$ python openambit2gpx.py in.sml out.xml

```
Traceback (most recent call last):
   File "openambit2gpx.py", line 196, in <module>
    if lapArray[i][0]=='Manual':
TypeError: 'int' object has no attribute '__getitem__'
```

>$ python 

```
Python 2.7.10 (default, Oct  6 2017, 22:29:07) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
```

**Comment by centic9** [comment]
Can you upload a sample log which causes this problem?

**Comment by centic9** [comment]
When taking another look I saw that you try to convert an "sml" file, which is what Suunto uses. But the openambit2gpx-tool is geared towards converting the Openambit XML format to GPX, the structure of this is different, there is no plan to support the Suunto format right now because Suunto announced end-of-life for it's toolchain in early 2020.

You can take a look at https://github.com/montant/ambit2gpx for a project which tries to do conversion form .sml to .gpx.
