### ISSUE TITLE
Question: Speed Unit in .log file

### ISSUE THREAD

**Issue by Tlkj4n24pi** [openambitproject/openambit#245]
Dear Community

I am using the awesome open-ambit package to sync the log files to my computer.
I have written my own code to convert it to .csv and process the data.

I have observed, that the speed data is a three digit integer number. Does anybody know and mind to tell me what units this is in? And what the ratio is to meter/second.

Best

**Comment by Tlkj4n24pi** [comment]
Could it be that it is in percentage of meter/second?
Such that:
ambitformat: 321 = 3.21 meter/second?

**Comment by vascotenner** [comment]
In the scripts directory there is a python script that converts log files to GPX files. This might give you a pointer.

However, since some time the speed readings in this GPX file are way to high.

**Comment by rnorris** [comment]
Yes the speed on the ambit log file is in 100ths of m/s.
This might come directly out of watch interface itself, possibly being an integer format (rather than a floating point).
Note the python script that converts log files to GPX file has an error in it regarding the speed, which I addressed with the pull request #219, however that has yet to be accepted into the main code base.

**Comment by centic9** [comment]
#219 is merged since some time now and I think the question is basically answered here, so closing this for now. 

Please report if there is still something wrong with the speed-readings.
